  /*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Command: npx gltfjsx@6.2.16 Bauhaus.glb 
  */

  import React, { useRef } from 'react'
  import { useGLTF } from '@react-three/drei'

  export   function ModelHouse(props) {
    const { nodes, materials } = useGLTF('/Bauhaus.glb')
    return (
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.MetalBars} position={[0.615, 1.364, -0.183]} scale={[0.007, 0.13, 0.007]} />
        <mesh geometry={nodes.BezierCurve001.geometry} material={materials.MetalBars} position={[0, 0.06, 0]} />
        <mesh geometry={nodes.Antenna.geometry} material={materials.wire_006135006} position={[1.761, 1.963, 0.633]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.003} />
        <mesh geometry={nodes.Text.geometry} material={materials['Material.001']} position={[0.626, 1.76, 0.331]} rotation={[-1.563, 0, 0]} scale={[-0.92, -1, -1.026]} />
        <mesh geometry={nodes.BauhausTop.geometry} material={materials.Material} />
        <mesh geometry={nodes.BalconyFat.geometry} material={materials.Material} position={[1.638, 0.793, -0.21]} scale={[0.464, 0.443, 0.443]} />
        <mesh geometry={nodes.BlaconyThinIn.geometry} material={materials.Material} position={[0.127, 0.874, -0.066]} rotation={[0, -1.518, 0]} scale={[0.464, 0.443, 0.443]} />
        <mesh geometry={nodes.Railing.geometry} material={materials.MetalBars} position={[1.98, 0.32, 0.181]} scale={[0.007, 0.13, 0.007]} />
        <mesh geometry={nodes.BezierCurve.geometry} material={materials.MetalBars} position={[1.642, 0.45, -0.205]} />
        <mesh geometry={nodes.BalconyBoxR.geometry} material={nodes.BalconyBoxR.material} position={[1.371, 0.22, 0.817]} scale={[0.229, 0.101, 0.229]} />
        <mesh geometry={nodes.BlaconyBoxLeft.geometry} material={nodes.BlaconyBoxLeft.material} position={[0.411, 0.22, 0.817]} scale={[0.229, 0.101, 0.229]} />
        <mesh geometry={nodes.RoofCube.geometry} material={materials.Material} position={[1.634, 1.793, 0.219]} />
        <mesh geometry={nodes.GlassL.geometry} material={materials.Glass} position={[1.28, 1.4, 0.869]} rotation={[0, 0, -Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.GlassR.geometry} material={materials.Glass} position={[1.427, 1.4, 0.869]} rotation={[0, 0, -Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.GlassL001.geometry} material={materials.Glass} position={[0.324, 1.4, 0.869]} rotation={[0, 0, -Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.GlassR001.geometry} material={materials.Glass} position={[0.471, 1.4, 0.869]} rotation={[0, 0, -Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.GlassL002.geometry} material={materials.Glass} position={[1.599, 0.411, -0.412]} rotation={[Math.PI, 0, Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.GlassR002.geometry} material={materials.Glass} position={[1.746, 0.411, -0.412]} rotation={[Math.PI, 0, Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.GlassL003.geometry} material={materials.Glass} position={[0.839, 0.356, -0.063]} rotation={[Math.PI, 0, Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.GlassR003.geometry} material={materials.Glass} position={[0.986, 0.356, -0.063]} rotation={[Math.PI, 0, Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.GlassL004.geometry} material={materials.Glass} position={[-0.087, 0.442, -0.494]} rotation={[Math.PI, 0, Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.GlassR004.geometry} material={materials.Glass} position={[0.06, 0.442, -0.494]} rotation={[Math.PI, 0, Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.RoofCube001.geometry} material={materials.Glass} position={[1.621, 1.867, 0.227]} scale={[1, 0.293, 1]} />
        <mesh geometry={nodes.RoofCube002.geometry} material={materials.Material} position={[1.634, 1.793, 0.219]} scale={0.935} />
        <mesh geometry={nodes.RoofCube003.geometry} material={materials.Glass} position={[1.419, 1.876, -0.299]} rotation={[-Math.PI, 1.06, -Math.PI]} scale={[1, 0.293, 1]} />
        <mesh geometry={nodes.GlassR005.geometry} material={materials.Glass} position={[1.71, 1.881, -0.374]} rotation={[Math.PI, 0, Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.GlassR006.geometry} material={materials.Glass} position={[1.541, 1.881, -0.374]} rotation={[Math.PI, 0, Math.PI]} scale={[0.053, 0.069, 0.001]} />
        <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[1.356, 1.4, 0.898]} rotation={[0, -1.563, 1.571]} scale={[1.037, 1, 2.822]} />
        <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[1.278, 1.4, 0.856]} rotation={[0, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
        <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[1.427, 1.4, 0.856]} rotation={[0, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
        <mesh geometry={nodes.BauhausTop001.geometry} material={materials.Material} scale={0.909} />
        <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0.399, 1.4, 0.898]} rotation={[0, -1.563, 1.571]} scale={[1.037, 1, 2.822]} />
        <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0.322, 1.4, 0.856]} rotation={[0, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
        <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[0.471, 1.4, 0.856]} rotation={[0, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
        <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[1.675, 0.416, -0.441]} rotation={[-Math.PI, -1.563, 1.571]} scale={[1.037, 1, 2.822]} />
        <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[1.597, 0.416, -0.399]} rotation={[-Math.PI, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
        <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[1.746, 0.416, -0.399]} rotation={[-Math.PI, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
        <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[0.916, 0.368, -0.101]} rotation={[0, -1.561, -Math.PI / 2]} scale={[1.037, 1, 2.822]} />
        <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[0.838, 0.368, -0.05]} rotation={[-3.142, -1.563, 1.571]} scale={[0.791, 2.061, 1.009]} />
        <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[0.987, 0.368, -0.05]} rotation={[-3.142, -1.563, 1.571]} scale={[0.791, 2.061, 1.009]} />
        <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-0.232, -0.172, -0.511]} scale={[0.108, 0.224, 0.034]} />
        <mesh geometry={nodes.BauhausTop003.geometry} material={materials.Material} position={[0, -0.515, 0]} />
        <mesh geometry={nodes.BauhausTop002.geometry} material={materials.Material} />
        <mesh geometry={nodes.BauhausTop004.geometry} material={materials.Material} position={[0, 0.452, 0]} />
        <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[-0.011, 0.448, -0.523]} rotation={[-Math.PI, -1.563, 1.571]} scale={[1.037, 1, 2.822]} />
        <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[-0.089, 0.448, -0.481]} rotation={[-Math.PI, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
        <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[0.06, 0.448, -0.481]} rotation={[-Math.PI, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
        <mesh geometry={nodes.BauhausTop005.geometry} material={materials.Material} position={[1.571, 0.825, 0.079]} />
        <mesh geometry={nodes.BauhausTop006.geometry} material={materials.Material} position={[1.409, 1.881, -0.302]} rotation={[-Math.PI, 1.06, -Math.PI]} />
        <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[1.736, 0.38, 1.071]} rotation={[-Math.PI, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
        <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[1.71, 1.88, -0.361]} rotation={[-Math.PI, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
        <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[1.541, 1.88, -0.361]} rotation={[-Math.PI, -1.563, 1.571]} scale={[0.791, 2.01, 1.009]} />
      </group>
    )
  }

  useGLTF.preload('/Bauhaus.glb')
